nats:
  image:
    tag: 'latest'
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '256Mi'
      cpu: '200m'
  metrics:
    enabled: true
  jetstream:
    enabled: false

natsBox:
    enabled: false
