namespace: fuel-data

helmDefaults:
  createNamespace: true

releases:
  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    values:
      -  ../../~monitoring/values-prom.yaml

  - name: prometheus-adapter
    chart: prometheus-community/prometheus-adapter
    values:
      -  ../../~monitoring/values-prom-adapter.yaml
    needs:
      - prometheus

  - name: keda
    chart: kedacore/keda
    values:
      - ../../~monitoring/values-keda.yaml

  - name: archive-nats
    chart: ../../archive-nats/chart
    values:
      - ../../archive-nats/chart/values.yaml
    needs:
      - prometheus
      - prometheus-adapter
    
  - name: relay-nats
    chart: nats/nats
    values:
      - ../../relay-nats/chart/values.yaml

  - name: fuel-data-grpc-edge
    chart: ../../fuel-data-grpc-edge/chart
    values:
      - ../../fuel-data-grpc-edge/chart/values-local.yaml
    needs:
      - archive-nats
      - relay-nats

  - name: fuel-archive-node
    chart: ../../fuel-archive-node/chart
    values:
      - ../../fuel-archive-node/chart/values-local.yaml
      - ../../fuel-archive-node/chart/values-{{ env "NETWORK" }}.yaml
      - ../../fuel-archive-node/chart/values-{{ env "NETWORK" }}-secret.yaml
    needs:
      - archive-nats

  - name: fuel-relay-node
    chart: ../../fuel-relay-node/chart
    values:
      - ../../fuel-relay-node/chart/values-local.yaml
      - ../../fuel-relay-node/chart/values-{{ env "NETWORK" }}.yaml
      - ../../fuel-relay-node/chart/values-{{ env "NETWORK" }}-secret.yaml
    needs:
      - relay-nats

