services:
  relay-nats:
    image: nats:latest
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
      - 8443:8443
    volumes:
      - ./nats/relay-nats.conf:/etc/nats/nats.conf
    command: [-m, '8222', --config=/etc/nats/nats.conf, -D]
    env_file:
      - ./../../.env
  archive-nats:
    image: nats:latest
    restart: always
    ports:
      - 4223:4222
      - 8223:8222
      - 8444:8443
    volumes:
      - ./archive-nats.conf:/etc/nats/nats.conf
    command: [-m, '8222', --js, --config=/etc/nats/nats.conf, -D]
    env_file:
      - ./../../.env