apiVersion: v1
kind: Service
metadata:
  name: fuel-data-grpc-edge
  labels:
    app: fuel-data-grpc-edge
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
  selector:
    app: fuel-data-grpc-edge
